<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Account successfully created</name>
   <tag></tag>
   <elementGuidId>f8fe1fa7-893f-48d5-a36b-684e73c7ba43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>372d4130-0f2d-4e81-a23a-e8752c987386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>3149a251-8035-41c1-a8a0-65ce38ea424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success col-lg-12 animated fadeInDown</value>
      <webElementGuid>c7e2e5d2-d85d-4fee-86d6-cf8ff843a020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account successfully created</value>
      <webElementGuid>56e12996-88bb-4bd9-8fff-f5453dff691a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success&quot;)</value>
      <webElementGuid>0e183a15-6501-45e0-ac40-cbb199484b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='success']</value>
      <webElementGuid>e7bbc9ae-e101-41d7-b4cd-9517e27e713c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password recovery'])[1]/preceding::div[31]</value>
      <webElementGuid>b8493415-df34-43e5-8f26-b3cc7f23fdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>3aed9e70-6075-4eca-83b0-5003636758c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'success' and (text() = 'Account successfully created' or . = 'Account successfully created')]</value>
      <webElementGuid>14670bf5-3c30-4417-9572-3be8c9448b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
